### ISSUE TITLE
Class error

### ISSUE THREAD

**Issue by Abuzar560** [zoelabbb/conio.h#10]
after including in vs code for c. the error show unknown type name 'class'.
for better understanding i am sharing the screenshot. thank you..
![Screenshot from 2022-11-08 10-19-04](https://user-images.githubusercontent.com/93877072/200477938-bc3ec96c-34e4-4f2a-b982-69bd661f5cab.png)

**Comment by zoelabbb** [comment]
Haii thanks for ur reply, yup !! thats right. This is just for C++ only dude
