### ISSUE TITLE
Program crashes with "Illegal instruction" error

### ISSUE THREAD

**Issue by Lukasiewski** [zoelabbb/conio.h#13]
I'm using the conio.h library for a project of mine, and when I'm using the getch() function it stops with a highlight at line 239 of conio.h with a message "Exception has occured. Illegal instruction". I am using vscode with C++ extention pack and code runner.

![Screenshot_20231214_173114](https://github.com/zoelabbb/conio.h/assets/147441867/64829cbc-45a1-45ee-86c1-153d85489975)

![Screenshot_20231214_173241](https://github.com/zoelabbb/conio.h/assets/147441867/6e64ba05-e4b1-42af-9888-d3cf82102f88)

**Comment by zoelabbb** [comment]
Illegal instruction errors don’t come from C++, they come instead from the operating system.

Maybe you can try this tutorial : 
- https://www.thewindowsclub.com/exception-illegal-instruction-error-on-windows

- https://copyprogramming.com/howto/illegal-instruction-when-programming-c-on-linux

**Comment by Lukasiewski** [comment]
Problem solved after changing

int getch(){
getch_echo(false);
}

to

int getch(){
return getch_echo(false);
}
