### ISSUE TITLE
Getting unknown type name 'class' error

### ISSUE THREAD

**Issue by yokesh004** [zoelabbb/conio.h#3]
![Screenshot from 2020-12-04 23-07-11](https://user-images.githubusercontent.com/59578892/101195543-926b7c00-3685-11eb-9cbb-a28e9f7eb52c.png)

**Comment by TheFenrisLycaon** [comment]
I second this !!! Any solution ??

**Comment by olupop** [comment]
C does not have classes. So, I think compiler does not understand class type and this file is not suitable for C (I am a beginner. I am just trying to understand too)

**Comment by yokesh004** [comment]
> C does not have classes. So, I think compiler does not understand class type and this file is not suitable for C (I am a beginner. I am just trying to understand too)

Thank you so much for clarifying it

**Comment by NeandertalModerno** [comment]
You need to run the file in terminal like this:
gcc example.cpp -o program -lstdc++

Then you open the file named 'program' like you usually do

**Comment by Lightsman7** [comment]
Me too! I don't know how to fix it. Please help me.

**Comment by Crazybat2022** [comment]
Me too! just a beginner.
![Screenshot 2024-05-21 01:04:46](https://github.com/zoelabbb/conio.h/assets/114375558/2a5652b6-668a-4920-b67a-c85c6beb5a66)

**Comment by Lightsman7** [comment]
conio.h is not support in Linux Operation System.You will try another way to learn.
