### ISSUE TITLE
Style issues 

### ISSUE THREAD

**Issue by MuratovAS** [zoelabbb/conio.h#6]
Good afternoon.
Something strange is happening in this repository.
Oh my god, bring the code style to uniformity. Even your indents are not correct.
Why there are examples and installation instructions in .h, this is unacceptable!
Why README.md resembles a birthday cake, why do I need emoji, your contacts, I NEED A NORMAL DESCRIPTION.
Do the normal installation instructions, I NEED TERMINAL COMMANDS to install.
I'm surprised that this came up as my first search query.

But thanks. I found in this heap of information noise, the information I needed to write my own solution. It is impossible to use this in its current form.

**Comment by zoelabbb** [comment]
Hi, I already do the installation instruction. Do you read until finish step by step ? I give the screen capture.
