### ISSUE TITLE
Use in apache licensed project...

### ISSUE THREAD

**Issue by jpenguin** [zoelabbb/conio.h#7]
I want to use your conio implementation in my Apache 2.0 licensed game via GIT submodules; somewhere I read that this is fine, some docs say it would have to be MPL/MIT/BSD.  Could you possibly clear this up for me?

**Comment by jpenguin** [comment]
I found an MIT licensed version I can use

**Comment by nocturn9x** [comment]
> I found an MIT licensed version I can use

Where?

**Comment by zoelabbb** [comment]
sure, yes I can do that for you

**Comment by jpenguin** [comment]
> > I found an MIT licensed version I can use
> 
> Where? 

https://github.com/thradams/conio

Had to use with 

extern "C"
